/**
 * Utility to process and normalize HTML content generated by TipTap Editor or API responses.
 * Specifically converts direct video file iframe embeds (<iframe src="...mp4">) into native HTML5 <video controls src="..."></video>
 * so Chrome and other browsers render direct video files natively with player controls.
 */
export function formatHtmlContent(content: any): string {
  if (!content) return '';

  let htmlStr = '';

  if (Array.isArray(content)) {
    htmlStr = content
      .map((item) => {
        if (typeof item !== 'string') return '';
        const trimmed = item.trim();
        if (trimmed.startsWith('<')) return trimmed;
        return `<p>${trimmed}</p>`;
      })
      .filter(Boolean)
      .join('');
  } else if (typeof content === 'string') {
    const trimmed = content.trim();
    if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
      try {
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed)) {
          htmlStr = parsed
            .map((item) => {
              if (typeof item !== 'string') return '';
              const t = item.trim();
              if (t.startsWith('<')) return t;
              return `<p>${t}</p>`;
            })
            .filter(Boolean)
            .join('');
        } else {
          htmlStr = content;
        }
      } catch {
        htmlStr = content;
      }
    } else {
      htmlStr = content;
    }
  } else {
    htmlStr = String(content);
  }

  if (!htmlStr) return '';

  // 1. Replace <iframe src="...mp4|webm|ogg|mov|mkv|avi"> with native <video controls src="...">
  htmlStr = htmlStr.replace(
    /<iframe[^>]*src=["']([^"']+\.(?:mp4|webm|ogg|mov|mkv|avi|flv|wmv)(?:\?[^"']*)?)["'][^>]*>\s*<\/iframe>/gi,
    '<video controls playsinline preload="metadata" src="$1" class="w-full rounded-xl my-4 max-h-[500px] shadow-sm bg-black"></video>'
  );

  // 2. Replace <iframe src=".../uploads/..."> with native <video controls src="..."> if src contains video extension or uploads path
  htmlStr = htmlStr.replace(
    /<iframe[^>]*src=["']([^"']*\/uploads\/[^"']+)["'][^>]*>\s*<\/iframe>/gi,
    (match, src) => {
      if (/\.(mp4|webm|ogg|mov|mkv|avi|flv|wmv)/i.test(src) || !/\.(jpg|jpeg|png|gif|webp|svg)/i.test(src)) {
        return `<video controls playsinline preload="metadata" src="${src}" class="w-full rounded-xl my-4 max-h-[500px] shadow-sm bg-black"></video>`;
      }
      return match;
    }
  );

  // 3. Ensure native <video> tags have controls, playsinline, and responsive styling
  htmlStr = htmlStr.replace(/<video(?![^>]*\bcontrols\b)/gi, '<video controls playsinline preload="metadata"');

  return htmlStr;
}

export function hasHtmlContent(content: any): boolean {
  const html = formatHtmlContent(content);
  if (!html) return false;
  const textOnly = html.replace(/<[^>]*>/g, '').trim();
  const hasMediaOrTable = html.includes('<img') || html.includes('<video') || html.includes('<iframe') || html.includes('<table');
  return textOnly.length > 0 || hasMediaOrTable;
}
